<?php
/** Run only with NORTHLINE_TESTING=1 in an isolated WordPress test database. */
use Northline\Brief;
use Northline\Database;
use Northline\Api;
use Northline\Mail;
use Northline\Content;
if (getenv('NORTHLINE_TESTING') !== '1') throw new RuntimeException('This test requires an isolated test installation.');
$count = 0;
function nl_check(bool $condition, string $message): void {
    global $count;
    if (!$condition) throw new RuntimeException($message);
    $count++;
    echo "PASS {$message}\n";
}
$brief = Brief::validate(['type' => 'kitchen', 'propertySize' => 1800, 'area' => 200, 'finish' => 'considered', 'timeline' => '6-12', 'budget' => '100-200', 'name' => 'Alex Integration', 'town' => 'Demo Town', 'priorities' => 'Improve daylight and create useful storage for everyday family life.', 'email' => 'integration@example.com', 'phone' => '', 'consent' => true]);
$key = wp_generate_uuid4();
$row = Database::save($brief, $key);
$id = (int) $row['id'];
nl_check(Database::byId($id) !== null, 'enquiry saved durably');
nl_check((int) Database::save($brief, $key)['id'] === $id, 'idempotent retry returns same enquiry');
try { Database::save(array_replace($brief, ['town' => 'Other Town']), $key); throw new RuntimeException('Expected key conflict'); }
catch (DomainException $e) { nl_check(true, 'different payload with same key rejected'); }
global $wpdb;
nl_check((int) $wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM ' . Database::table('outbox') . ' WHERE enquiry_id=%d', $id)) === 2, 'receipt and staff outbox committed with brief');
$reject = static fn () => false;
add_filter('pre_wp_mail', $reject, 10, 2);
Mail::process();
remove_filter('pre_wp_mail', $reject, 10);
nl_check(Database::byId($id) !== null, 'email failure does not discard enquiry');
nl_check($wpdb->get_var($wpdb->prepare('SELECT status FROM ' . Database::table('outbox') . ' WHERE enquiry_id=%d AND kind=%s', $id, 'receipt')) === 'failed', 'email failure recorded');
$wpdb->query($wpdb->prepare('UPDATE ' . Database::table('outbox') . ' SET next_attempt=%s WHERE enquiry_id=%d', gmdate('Y-m-d H:i:s', time() - 1), $id));
$accept = static fn () => true;
add_filter('pre_wp_mail', $accept, 10, 2);
Mail::process();
remove_filter('pre_wp_mail', $accept, 10);
nl_check($wpdb->get_var($wpdb->prepare('SELECT status FROM ' . Database::table('outbox') . ' WHERE enquiry_id=%d AND kind=%s', $id, 'receipt')) === 'accepted', 'failed transport can recover');
wp_set_current_user(0);
$request = new WP_REST_Request('GET', '/northline/v1/brief/' . $row['public_id']);
$request->set_param('id', $row['public_id']);
nl_check(is_wp_error(Api::authorized($request)), 'private brief denied without credential');
$request->set_header('Authorization', 'Bearer ' . Database::token($row));
nl_check(Api::authorized($request) === true, 'valid private credential accepted');
$available = Api::availableSlots();
nl_check(count($available) > 0, 'future consultation slots generated');
$book = new WP_REST_Request('POST', '/northline/v1/brief/' . $row['public_id'] . '/booking');
$book->set_param('id', $row['public_id']);
$book->set_header('Content-Type', 'application/json');
$book->set_body(wp_json_encode(['slot' => $available[0]['value']]));
$result = Api::book($book);
nl_check(!is_wp_error($result) && $result->get_status() === 201, 'consultation reserved');
nl_check(!is_wp_error(Api::book($book)), 'booking retry is idempotent');
$second = Database::save(array_replace($brief, ['email' => 'second@example.com']), wp_generate_uuid4());
$book->set_param('id', $second['public_id']);
$conflict = Api::book($book);
nl_check(is_wp_error($conflict) && $conflict->get_error_data()['status'] === 409, 'occupied slot cannot be double booked');
$bad = new WP_REST_Request('POST', '/northline/v1/enquiries');
$bad->set_header('Content-Type', 'application/json');
$bad->set_header('Idempotency-Key', wp_generate_uuid4());
$bad->set_body(wp_json_encode($brief + ['website' => 'spam.example', 'challenge' => Api::challengeValue(time() - 5)]));
nl_check(is_wp_error(Api::submit($bad)), 'honeypot rejected');
$bad->set_body(wp_json_encode(array_replace($brief, ['email' => 'invalid', 'website' => '', 'challenge' => Api::challengeValue(time() - 5)])));
$invalid = Api::submit($bad);
nl_check(is_wp_error($invalid) && isset($invalid->get_error_data()['fields']['email']), 'field-specific server validation');
$bad->set_body(wp_json_encode($brief + ['website' => '', 'challenge' => Api::challengeValue(time() - 5)]));
$valid = Api::submit($bad);
nl_check(!is_wp_error($valid) && $valid->get_status() === 201, 'signed submission route succeeds');
$third = Database::enquiry($valid->get_data()['publicId']);
$before = get_page_by_path('studio');
$edited = '<!-- wp:paragraph --><p>Editor-owned content must survive seeding.</p><!-- /wp:paragraph -->';
wp_update_post(['ID' => $before->ID, 'post_content' => $edited]);
Content::seed();
nl_check(get_post($before->ID)->post_content === $edited, 'installer preserves editor changes');
wp_update_post(['ID' => $before->ID, 'post_content' => $before->post_content]);
nl_check((int) wp_count_posts('nl_project')->publish === 6, 'six editable case studies installed');
nl_check(count(Database::exportPersonalData('integration@example.com')['data']) >= 1, 'personal-data exporter returns brief');
Database::delete($id);
nl_check(Database::byId($id) === null, 'erasure removes brief');
foreach (['uploads', 'outbox', 'bookings'] as $table) nl_check((int) $wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM ' . Database::table($table) . ' WHERE enquiry_id=%d', $id)) === 0, 'erasure removes related ' . $table);
Database::delete((int) $second['id']);
Database::delete((int) $third['id']);
echo "{$count} WordPress integration assertions passed. No real email was sent.\n";
