"""Generate the brand's CSS tokens from the shared, Figma-ready JSON foundation."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
tokens = json.loads((ROOT / 'creative/material-space.tokens.json').read_text())
lines = ['/* Generated by tools/build-design.py. Edit creative/material-space.tokens.json. */', ':root {']
for name, value in tokens['color'].items():
    lines.append(f'  --md-sys-color-{name}: {value};')
for name, value in tokens['shape'].items():
    lines.append(f'  --md-sys-shape-corner-{name}: {value}px;')
for name, value in tokens['space'].items():
    lines.append(f'  --nl-space-{name}: {value}px;')
for name, value in tokens['type'].items():
    lines.append(f'  --md-ref-typeface-{name}: {value};')
for name, value in tokens['motion'].items():
    lines.append(f'  --nl-motion-{name}: {str(value) + "ms" if isinstance(value,int) else value};')
lines.append('}')
path = ROOT / 'theme/northline/assets/tokens.css'
path.write_text('\n'.join(lines)+'\n')
print(path.relative_to(ROOT))
